@baseUrl = http://localhost:2929/api


### 🔍 Health
GET http://localhost:2929/health



### 🧑 AUTH ----------------------------

### Register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "username": "rushi",
  "email": "rushi@gmail.com",
  "password": "123456"
}


### Login (cookie will be set automatically in browser/Postman)
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "rushikesh1@gmail.com",
  "password": "654321"
}

### Login (cookie will be set automatically in browser/Postman)
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "rushi@gmail.com",
  "password": "123456"
}


### Get Profile
GET {{baseUrl}}/auth/me


### Update Profile
PATCH {{baseUrl}}/auth/update-profile
Content-Type: application/json

{
  "username": "rushikesh-updated"
}


### Change Password
PUT {{baseUrl}}/auth/change-password
Content-Type: application/json

{
  "currentPassword": "123456",
  "newPassword": "654321"
}


### Logout
GET {{baseUrl}}/auth/logout


### Get All Users
GET {{baseUrl}}/auth/users



### 📦 REPOSITORIES --------------------

### Create Repo
POST {{baseUrl}}/repos
Content-Type: application/json

{
  "name": "sample-repo1",
  "description": "Sample desc1",
  "visibility": "public"
}


### Get All Repos
GET {{baseUrl}}/repos


### Get Repo
GET {{baseUrl}}/repos/69b7cc932a97f90866c47f33


### Update Repo
PATCH {{baseUrl}}/repos/69b8eb7289e1e854ba4a96f8
Content-Type: application/json

{
  "name": "updated-repo-name",
  "visibility":"private"
}


### Delete Repo
DELETE {{baseUrl}}/repos/69b8eacd89e1e854ba4a96ed



### 👥 COLLABORATORS -------------------

### Add Collaborator
POST {{baseUrl}}/repos/69b8eb7289e1e854ba4a96f8/collaborators
Content-Type: application/json

{
  "userId": "69b7cc622a97f90866c47f2b",
  "role": "collaborator"
}


### Get Collaborators
GET {{baseUrl}}/repos/69b8eb7289e1e854ba4a96f8/collaborators


### Update Role
PATCH {{baseUrl}}/repos/69b8eb7289e1e854ba4a96f8/collaborators/69b7cc622a97f90866c47f2b
Content-Type: application/json

{
  "role": "viewer"
}


### Remove Collaborator
DELETE {{baseUrl}}/repos/69b7cc932a97f90866c47f33/collaborators/69b7cc622a97f90866c47f2b



# ### 📁 FILES ---------------------------

# ### Upload File
# POST {{baseUrl}}/files/upload
# Content-Type: multipart/form-data

# file=@test.js
# repository={{repoId}}


# ### Upload Multiple Files
# POST {{baseUrl}}/files/upload-multiple
# Content-Type: multipart/form-data

# files=@index.js
# files=@app.js
# repository={{repoId}}


# ### Get Repo Files
# GET {{baseUrl}}/files/repo/{{repoId}}


# ### Get File
# GET {{baseUrl}}/files/{{fileId}}


# ### Update File
# PUT {{baseUrl}}/files/{{fileId}}
# Content-Type: multipart/form-data

# file=@updated.js


# ### Delete File
# DELETE {{baseUrl}}/files/{{fileId}}



### 📝 COMMITS -------------------------

### Create Commit
POST {{baseUrl}}/commits
Content-Type: application/json

{
  "repository": "69b8eb7289e1e854ba4a96f8",
  "message": "Second commit"
}


### Get Commits
GET {{baseUrl}}/commits/repo/69b8eb7289e1e854ba4a96f8


### Get Commit
GET {{baseUrl}}/commits/69b8f5a53a9711b08b73c7ba


### Update Commit
PATCH {{baseUrl}}/commits/69b8f5a53a9711b08b73c7ba
Content-Type: application/json

{
  "message": "Updated commit message"
}


### Delete Commit
DELETE {{baseUrl}}/commits/69b8f5a53a9711b08b73c7ba



# ### 🔀 PULL REQUESTS -------------------

### Create PR
POST {{baseUrl}}/pull-requests
Content-Type: application/json

{
  "repository": "69b8eb7289e1e854ba4a96f8",
  "title": "New Feature",
  "description": "Added login feature"
}


### Get PRs
GET {{baseUrl}}/pull-requests/repo/69b8eb7289e1e854ba4a96f8


### Get PR
GET {{baseUrl}}/pull-requests/69b9127aff537928ead9c35e


### Merge PR
PATCH {{baseUrl}}/pull-requests/69b9127aff537928ead9c35e/merge


### Close PR
PATCH {{baseUrl}}/pull-requests/69b9127aff537928ead9c35e/close


### Reopen PR
PATCH {{baseUrl}}/pull-requests/69b9127aff537928ead9c35e/reopen


### Update PR
PUT {{baseUrl}}/pull-requests/69b9127aff537928ead9c35e
Content-Type: application/json

{
  "title": "Updated PR title"
}


### Delete PR
DELETE {{baseUrl}}/pull-requests/69b9127aff537928ead9c35e



### 🐞 ISSUES --------------------------

### Create Issue
POST {{baseUrl}}/issues
Content-Type: application/json

{
  "repository": "69b8eb7289e1e854ba4a96f8",
  "title": "Bug in login",
  "description": "Login button not working"
}


### Get Issues
GET {{baseUrl}}/issues/repo/69b8eb7289e1e854ba4a96f8


### Get Issue
GET {{baseUrl}}/issues/69b916aaff537928ead9c37a


### Close Issue
PATCH {{baseUrl}}/issues/69b916aaff537928ead9c37a/close/


### Reopen Issue
PATCH {{baseUrl}}/issues/69b916aaff537928ead9c37a/reopen/


### Update Issue
PUT {{baseUrl}}/issues/69b916aaff537928ead9c37a/
Content-Type: application/json

{
  "title": "Updated issue title"
}


### Delete Issue
DELETE {{baseUrl}}/issues/69b916aaff537928ead9c37a



### 💬 COMMENTS ------------------------

### Add Comment
POST {{baseUrl}}/comments/
Content-Type: application/json

{
  "issue": "69b91833ff537928ead9c388",
  "text": "issue with login button"
}


### Get Comments
GET {{baseUrl}}/comments/issue/69b91833ff537928ead9c388


### Get Comment
GET {{baseUrl}}/comments/69b91d4dff537928ead9c39a


### Update Comment
PUT {{baseUrl}}/comments/69b91d4dff537928ead9c39a
Content-Type: application/json

{
  "text": "Updated comment"
}


### Delete Comment
DELETE {{baseUrl}}/comments/69b91d4dff537928ead9c39a